# Generated by Django 2.2.1 on 2021-04-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210415_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
