# Generated by Django 2.2.1 on 2021-04-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userinformation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='status',
            field=models.CharField(max_length=200),
        ),
    ]
