# Generated by Django 2.2.1 on 2021-04-15 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210415_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformation',
            old_name='note',
            new_name='device_model',
        ),
    ]
