# Generated by Django 2.2.1 on 2021-04-15 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210415_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='classmate',
            field=models.CharField(max_length=100, verbose_name='Khóa học/lớp học'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='device_mac_address',
            field=models.CharField(max_length=20, verbose_name='Địa chỉ MAC của thiết bị'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='device_model',
            field=models.CharField(max_length=1000, verbose_name='Tên thiết bị'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.DeviceType', verbose_name='Loại thiết bị'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='email',
            field=models.CharField(max_length=1000, unique=True, verbose_name='Địa chỉ email'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Họ và tên sinh viên'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='phone',
            field=models.IntegerField(null=True, verbose_name='Số điện thoại đăng ký'),
        ),
    ]
