# Generated by Django 2.2.1 on 2021-04-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210415_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='ap_mac_address',
            field=models.CharField(default=1, max_length=20, verbose_name='Địa chỉ MAC của AP'),
            preserve_default=False,
        ),
    ]
