# Generated by Django 3.1.3 on 2021-04-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_userinformation_ap_mac_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Địa chỉ email'),
        ),
    ]
