# Generated by Django 3.1.3 on 2021-04-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210416_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='device_mac_address',
            field=models.CharField(max_length=20, unique=True, verbose_name='Địa chỉ MAC của thiết bị'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='email',
            field=models.CharField(max_length=1000, unique=True, verbose_name='Địa chỉ email'),
        ),
    ]
