# Generated by Django 3.1.3 on 2021-04-17 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_userdetalmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetalModel',
        ),
    ]
