# Generated by Django 3.2.1 on 2021-05-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_delete_userdetalmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='email',
            field=models.CharField(max_length=1000, verbose_name='Địa chỉ email'),
        ),
    ]
