# Generated by Django 3.1.3 on 2021-05-05 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_userinformation_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
