# Generated by Django 3.1.3 on 2021-05-05 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210505_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='phone',
            field=models.IntegerField(default=1, verbose_name='Số điện thoại đăng ký'),
            preserve_default=False,
        ),
    ]
