# Generated by Django 3.1.3 on 2021-05-05 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210505_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='code',
            field=models.IntegerField(null=True),
        ),
    ]
