# Generated by Django 3.1.3 on 2021-05-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20210506_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='bw_download',
            field=models.IntegerField(default=10000, verbose_name='Băng thông download'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='bw_upload',
            field=models.IntegerField(default=10000, verbose_name='Băng thông upload'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='time_used',
            field=models.IntegerField(default=60, verbose_name='Thời gian sử dụng'),
        ),
    ]
