# Generated by Django 3.2.1 on 2021-05-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20210510_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinformation',
            name='student_email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
