# Generated by Django 3.2.1 on 2021-05-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_studentinformation_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinformation',
            name='student_first_name',
        ),
        migrations.RemoveField(
            model_name='studentinformation',
            name='student_last_name',
        ),
        migrations.AddField(
            model_name='studentinformation',
            name='student_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
