# Generated by Django 3.2.1 on 2021-06-07 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210511_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='status',
            field=models.ForeignKey(default='DEACTIVE', on_delete=django.db.models.deletion.CASCADE, to='main.userstatusmodel'),
        ),
    ]
