# Generated by Django 3.2.1 on 2021-06-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20210607_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='status',
            field=models.CharField(default='DEACTIVE', max_length=200, verbose_name='Trạng thái'),
        ),
    ]
